version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: postgres
      - image: circleci/postgres:10.3-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
    steps:
      - checkout

      # Cache Restoration
      - restore_cache:
          keys:
            - travel-blog-{{ checksum "Gemfile.lock" }}
            - travel-blog-

      # Update Dependencies
      # - run: bundle install --path vendor/bundle
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.1.4
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            yarn install
      - save_cache:
          key: travel-blog-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - save_cache:
          key: travel-blog-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn-cache

      # Setup script
      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
      # Linting
      - run: bundle exec rubocop --parallel
      - run: yarn lint

      # Run tests
      - run: bundle exec rspec
      - run: yarn test:ci

      - store_artifacts:
          path: tmp/screenshot/s